#ifndef RENDSETTINGS_H
#define RENDSETTINGS_H

#define GAM_WIDTH_ACTUAL 840
#define GAM_HEIGHT_ACTUAL 640
#define RES_SCALE 1
#define GAM_WIDTH GAM_WIDTH_ACTUAL/RES_SCALE
#define GAM_HEIGHT GAM_HEIGHT_ACTUAL/RES_SCALE
#define GAM_START_X 250
#define GAM_START_Y 250

#endif
